-- Auto-generated from schema-map-postgres.yaml (map@94ebe6c)
-- engine: postgres
-- table:  coupons

CREATE TABLE IF NOT EXISTS coupons (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL,
  code VARCHAR(100) NOT NULL,
  code_ci TEXT GENERATED ALWAYS AS (lower(code)) STORED,
  type TEXT NOT NULL,
  value NUMERIC(12,2) NOT NULL,
  currency CHAR(3) NULL,
  starts_at DATE NOT NULL,
  ends_at DATE NULL,
  max_redemptions INTEGER NOT NULL DEFAULT 0,
  min_order_amount NUMERIC(12,2) NULL,
  applies_to JSONB NULL,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  CONSTRAINT chk_coupon_percent_fixed
    CHECK (
      (type='percent' AND value BETWEEN 0 AND 100 AND currency IS NULL)
      OR
      (type='fixed'   AND value >= 0 AND currency ~ '^[A-Z]{3}$')
    ),
  CONSTRAINT chk_coupons_range
    CHECK (ends_at IS NULL OR ends_at >= starts_at)
);
